DROP TABLE IF EXISTS volunteer;
DROP TABLE IF EXISTS donor;
DROP TABLE IF EXISTS creates;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS person_phone_number;
DROP TABLE IF EXISTS food_item;
DROP TABLE IF EXISTS household;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS community;
DROP TABLE IF EXISTS partner_agency;

DROP EXTENSION IF EXISTS pgcrypto;